// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.tencent.mars.sample.chat.proto {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class Chat {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.SendMessageRequest, global::com.tencent.mars.sample.chat.proto.SendMessageRequest.Builder> internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.SendMessageResponse, global::com.tencent.mars.sample.chat.proto.SendMessageResponse.Builder> internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static Chat() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "CgpjaGF0LnByb3RvEiJjb20udGVuY2VudC5tYXJzLnNhbXBsZS5jaGF0LnBy" + 
          "b3RvImEKElNlbmRNZXNzYWdlUmVxdWVzdBIUCgxhY2Nlc3NfdG9rZW4YASAC" + 
          "KAkSDAoEZnJvbRgCIAIoCRIKCgJ0bxgDIAIoCRIMCgR0ZXh0GAQgAigJEg0K" + 
          "BXRvcGljGAUgAigJIo4BChNTZW5kTWVzc2FnZVJlc3BvbnNlEhAKCGVycl9j" + 
          "b2RlGAEgAigFEg8KB2Vycl9tc2cYAiACKAkSDAoEZnJvbRgDIAIoCRIMCgR0" + 
          "ZXh0GAQgAigJEg0KBXRvcGljGAUgAigJIikKBUVycm9yEgoKBkVSUl9PSxAA" + 
          "EhQKB0VSUl9TWVMQ////////////AQ==");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.SendMessageRequest, global::com.tencent.mars.sample.chat.proto.SendMessageRequest.Builder>(internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__Descriptor,
                new string[] { "AccessToken", "From", "To", "Text", "Topic", });
        internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__Descriptor = Descriptor.MessageTypes[1];
        internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.SendMessageResponse, global::com.tencent.mars.sample.chat.proto.SendMessageResponse.Builder>(internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__Descriptor,
                new string[] { "ErrCode", "ErrMsg", "From", "Text", "Topic", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class SendMessageRequest : pb::GeneratedMessage<SendMessageRequest, SendMessageRequest.Builder> {
    private SendMessageRequest() { }
    private static readonly SendMessageRequest defaultInstance = new SendMessageRequest().MakeReadOnly();
    private static readonly string[] _sendMessageRequestFieldNames = new string[] { "access_token", "from", "text", "to", "topic" };
    private static readonly uint[] _sendMessageRequestFieldTags = new uint[] { 10, 18, 34, 26, 42 };
    public static SendMessageRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override SendMessageRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override SendMessageRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.chat.proto.Chat.internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<SendMessageRequest, SendMessageRequest.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.chat.proto.Chat.internal__static_com_tencent_mars_sample_chat_proto_SendMessageRequest__FieldAccessorTable; }
    }
    
    public const int AccessTokenFieldNumber = 1;
    private bool hasAccessToken;
    private string accessToken_ = "";
    public bool HasAccessToken {
      get { return hasAccessToken; }
    }
    public string AccessToken {
      get { return accessToken_; }
    }
    
    public const int FromFieldNumber = 2;
    private bool hasFrom;
    private string from_ = "";
    public bool HasFrom {
      get { return hasFrom; }
    }
    public string From {
      get { return from_; }
    }
    
    public const int ToFieldNumber = 3;
    private bool hasTo;
    private string to_ = "";
    public bool HasTo {
      get { return hasTo; }
    }
    public string To {
      get { return to_; }
    }
    
    public const int TextFieldNumber = 4;
    private bool hasText;
    private string text_ = "";
    public bool HasText {
      get { return hasText; }
    }
    public string Text {
      get { return text_; }
    }
    
    public const int TopicFieldNumber = 5;
    private bool hasTopic;
    private string topic_ = "";
    public bool HasTopic {
      get { return hasTopic; }
    }
    public string Topic {
      get { return topic_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasAccessToken) return false;
        if (!hasFrom) return false;
        if (!hasTo) return false;
        if (!hasText) return false;
        if (!hasTopic) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _sendMessageRequestFieldNames;
      if (hasAccessToken) {
        output.WriteString(1, field_names[0], AccessToken);
      }
      if (hasFrom) {
        output.WriteString(2, field_names[1], From);
      }
      if (hasTo) {
        output.WriteString(3, field_names[3], To);
      }
      if (hasText) {
        output.WriteString(4, field_names[2], Text);
      }
      if (hasTopic) {
        output.WriteString(5, field_names[4], Topic);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasAccessToken) {
          size += pb::CodedOutputStream.ComputeStringSize(1, AccessToken);
        }
        if (hasFrom) {
          size += pb::CodedOutputStream.ComputeStringSize(2, From);
        }
        if (hasTo) {
          size += pb::CodedOutputStream.ComputeStringSize(3, To);
        }
        if (hasText) {
          size += pb::CodedOutputStream.ComputeStringSize(4, Text);
        }
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(5, Topic);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static SendMessageRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static SendMessageRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static SendMessageRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SendMessageRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private SendMessageRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(SendMessageRequest prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<SendMessageRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(SendMessageRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private SendMessageRequest result;
      
      private SendMessageRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          SendMessageRequest original = result;
          result = new SendMessageRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override SendMessageRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.chat.proto.SendMessageRequest.Descriptor; }
      }
      
      public override SendMessageRequest DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.chat.proto.SendMessageRequest.DefaultInstance; }
      }
      
      public override SendMessageRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is SendMessageRequest) {
          return MergeFrom((SendMessageRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(SendMessageRequest other) {
        if (other == global::com.tencent.mars.sample.chat.proto.SendMessageRequest.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasAccessToken) {
          AccessToken = other.AccessToken;
        }
        if (other.HasFrom) {
          From = other.From;
        }
        if (other.HasTo) {
          To = other.To;
        }
        if (other.HasText) {
          Text = other.Text;
        }
        if (other.HasTopic) {
          Topic = other.Topic;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_sendMessageRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _sendMessageRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasAccessToken = input.ReadString(ref result.accessToken_);
              break;
            }
            case 18: {
              result.hasFrom = input.ReadString(ref result.from_);
              break;
            }
            case 26: {
              result.hasTo = input.ReadString(ref result.to_);
              break;
            }
            case 34: {
              result.hasText = input.ReadString(ref result.text_);
              break;
            }
            case 42: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasAccessToken {
        get { return result.hasAccessToken; }
      }
      public string AccessToken {
        get { return result.AccessToken; }
        set { SetAccessToken(value); }
      }
      public Builder SetAccessToken(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasAccessToken = true;
        result.accessToken_ = value;
        return this;
      }
      public Builder ClearAccessToken() {
        PrepareBuilder();
        result.hasAccessToken = false;
        result.accessToken_ = "";
        return this;
      }
      
      public bool HasFrom {
        get { return result.hasFrom; }
      }
      public string From {
        get { return result.From; }
        set { SetFrom(value); }
      }
      public Builder SetFrom(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFrom = true;
        result.from_ = value;
        return this;
      }
      public Builder ClearFrom() {
        PrepareBuilder();
        result.hasFrom = false;
        result.from_ = "";
        return this;
      }
      
      public bool HasTo {
        get { return result.hasTo; }
      }
      public string To {
        get { return result.To; }
        set { SetTo(value); }
      }
      public Builder SetTo(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTo = true;
        result.to_ = value;
        return this;
      }
      public Builder ClearTo() {
        PrepareBuilder();
        result.hasTo = false;
        result.to_ = "";
        return this;
      }
      
      public bool HasText {
        get { return result.hasText; }
      }
      public string Text {
        get { return result.Text; }
        set { SetText(value); }
      }
      public Builder SetText(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder ClearText() {
        PrepareBuilder();
        result.hasText = false;
        result.text_ = "";
        return this;
      }
      
      public bool HasTopic {
        get { return result.hasTopic; }
      }
      public string Topic {
        get { return result.Topic; }
        set { SetTopic(value); }
      }
      public Builder SetTopic(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTopic = true;
        result.topic_ = value;
        return this;
      }
      public Builder ClearTopic() {
        PrepareBuilder();
        result.hasTopic = false;
        result.topic_ = "";
        return this;
      }
    }
    static SendMessageRequest() {
      object.ReferenceEquals(global::com.tencent.mars.sample.chat.proto.Chat.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class SendMessageResponse : pb::GeneratedMessage<SendMessageResponse, SendMessageResponse.Builder> {
    private SendMessageResponse() { }
    private static readonly SendMessageResponse defaultInstance = new SendMessageResponse().MakeReadOnly();
    private static readonly string[] _sendMessageResponseFieldNames = new string[] { "err_code", "err_msg", "from", "text", "topic" };
    private static readonly uint[] _sendMessageResponseFieldTags = new uint[] { 8, 18, 26, 34, 42 };
    public static SendMessageResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override SendMessageResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override SendMessageResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.chat.proto.Chat.internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<SendMessageResponse, SendMessageResponse.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.chat.proto.Chat.internal__static_com_tencent_mars_sample_chat_proto_SendMessageResponse__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static class Types {
      [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
      public enum Error {
        ERR_OK = 0,
        ERR_SYS = -1,
      }
      
    }
    #endregion
    
    public const int ErrCodeFieldNumber = 1;
    private bool hasErrCode;
    private int errCode_;
    public bool HasErrCode {
      get { return hasErrCode; }
    }
    public int ErrCode {
      get { return errCode_; }
    }
    
    public const int ErrMsgFieldNumber = 2;
    private bool hasErrMsg;
    private string errMsg_ = "";
    public bool HasErrMsg {
      get { return hasErrMsg; }
    }
    public string ErrMsg {
      get { return errMsg_; }
    }
    
    public const int FromFieldNumber = 3;
    private bool hasFrom;
    private string from_ = "";
    public bool HasFrom {
      get { return hasFrom; }
    }
    public string From {
      get { return from_; }
    }
    
    public const int TextFieldNumber = 4;
    private bool hasText;
    private string text_ = "";
    public bool HasText {
      get { return hasText; }
    }
    public string Text {
      get { return text_; }
    }
    
    public const int TopicFieldNumber = 5;
    private bool hasTopic;
    private string topic_ = "";
    public bool HasTopic {
      get { return hasTopic; }
    }
    public string Topic {
      get { return topic_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasErrCode) return false;
        if (!hasErrMsg) return false;
        if (!hasFrom) return false;
        if (!hasText) return false;
        if (!hasTopic) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _sendMessageResponseFieldNames;
      if (hasErrCode) {
        output.WriteInt32(1, field_names[0], ErrCode);
      }
      if (hasErrMsg) {
        output.WriteString(2, field_names[1], ErrMsg);
      }
      if (hasFrom) {
        output.WriteString(3, field_names[2], From);
      }
      if (hasText) {
        output.WriteString(4, field_names[3], Text);
      }
      if (hasTopic) {
        output.WriteString(5, field_names[4], Topic);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasErrCode) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, ErrCode);
        }
        if (hasErrMsg) {
          size += pb::CodedOutputStream.ComputeStringSize(2, ErrMsg);
        }
        if (hasFrom) {
          size += pb::CodedOutputStream.ComputeStringSize(3, From);
        }
        if (hasText) {
          size += pb::CodedOutputStream.ComputeStringSize(4, Text);
        }
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(5, Topic);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static SendMessageResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static SendMessageResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static SendMessageResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SendMessageResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private SendMessageResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(SendMessageResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<SendMessageResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(SendMessageResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private SendMessageResponse result;
      
      private SendMessageResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          SendMessageResponse original = result;
          result = new SendMessageResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override SendMessageResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.chat.proto.SendMessageResponse.Descriptor; }
      }
      
      public override SendMessageResponse DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.chat.proto.SendMessageResponse.DefaultInstance; }
      }
      
      public override SendMessageResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is SendMessageResponse) {
          return MergeFrom((SendMessageResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(SendMessageResponse other) {
        if (other == global::com.tencent.mars.sample.chat.proto.SendMessageResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasErrCode) {
          ErrCode = other.ErrCode;
        }
        if (other.HasErrMsg) {
          ErrMsg = other.ErrMsg;
        }
        if (other.HasFrom) {
          From = other.From;
        }
        if (other.HasText) {
          Text = other.Text;
        }
        if (other.HasTopic) {
          Topic = other.Topic;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_sendMessageResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _sendMessageResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasErrCode = input.ReadInt32(ref result.errCode_);
              break;
            }
            case 18: {
              result.hasErrMsg = input.ReadString(ref result.errMsg_);
              break;
            }
            case 26: {
              result.hasFrom = input.ReadString(ref result.from_);
              break;
            }
            case 34: {
              result.hasText = input.ReadString(ref result.text_);
              break;
            }
            case 42: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasErrCode {
        get { return result.hasErrCode; }
      }
      public int ErrCode {
        get { return result.ErrCode; }
        set { SetErrCode(value); }
      }
      public Builder SetErrCode(int value) {
        PrepareBuilder();
        result.hasErrCode = true;
        result.errCode_ = value;
        return this;
      }
      public Builder ClearErrCode() {
        PrepareBuilder();
        result.hasErrCode = false;
        result.errCode_ = 0;
        return this;
      }
      
      public bool HasErrMsg {
        get { return result.hasErrMsg; }
      }
      public string ErrMsg {
        get { return result.ErrMsg; }
        set { SetErrMsg(value); }
      }
      public Builder SetErrMsg(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrMsg = true;
        result.errMsg_ = value;
        return this;
      }
      public Builder ClearErrMsg() {
        PrepareBuilder();
        result.hasErrMsg = false;
        result.errMsg_ = "";
        return this;
      }
      
      public bool HasFrom {
        get { return result.hasFrom; }
      }
      public string From {
        get { return result.From; }
        set { SetFrom(value); }
      }
      public Builder SetFrom(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFrom = true;
        result.from_ = value;
        return this;
      }
      public Builder ClearFrom() {
        PrepareBuilder();
        result.hasFrom = false;
        result.from_ = "";
        return this;
      }
      
      public bool HasText {
        get { return result.hasText; }
      }
      public string Text {
        get { return result.Text; }
        set { SetText(value); }
      }
      public Builder SetText(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder ClearText() {
        PrepareBuilder();
        result.hasText = false;
        result.text_ = "";
        return this;
      }
      
      public bool HasTopic {
        get { return result.hasTopic; }
      }
      public string Topic {
        get { return result.Topic; }
        set { SetTopic(value); }
      }
      public Builder SetTopic(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTopic = true;
        result.topic_ = value;
        return this;
      }
      public Builder ClearTopic() {
        PrepareBuilder();
        result.hasTopic = false;
        result.topic_ = "";
        return this;
      }
    }
    static SendMessageResponse() {
      object.ReferenceEquals(global::com.tencent.mars.sample.chat.proto.Chat.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
