// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.tencent.mars.sample.chat.proto {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class Messagepush {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_chat_proto_MessagePush__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.MessagePush, global::com.tencent.mars.sample.chat.proto.MessagePush.Builder> internal__static_com_tencent_mars_sample_chat_proto_MessagePush__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static Messagepush() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "ChFtZXNzYWdlcHVzaC5wcm90bxIiY29tLnRlbmNlbnQubWFycy5zYW1wbGUu" + 
          "Y2hhdC5wcm90byI7CgtNZXNzYWdlUHVzaBINCgV0b3BpYxgBIAIoCRIPCgdj" + 
          "b250ZW50GAIgAigJEgwKBGZyb20YAyACKAk=");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_tencent_mars_sample_chat_proto_MessagePush__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_tencent_mars_sample_chat_proto_MessagePush__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.MessagePush, global::com.tencent.mars.sample.chat.proto.MessagePush.Builder>(internal__static_com_tencent_mars_sample_chat_proto_MessagePush__Descriptor,
                new string[] { "Topic", "Content", "From", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MessagePush : pb::GeneratedMessage<MessagePush, MessagePush.Builder> {
    private MessagePush() { }
    private static readonly MessagePush defaultInstance = new MessagePush().MakeReadOnly();
    private static readonly string[] _messagePushFieldNames = new string[] { "content", "from", "topic" };
    private static readonly uint[] _messagePushFieldTags = new uint[] { 18, 26, 10 };
    public static MessagePush DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MessagePush DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MessagePush ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.chat.proto.Messagepush.internal__static_com_tencent_mars_sample_chat_proto_MessagePush__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MessagePush, MessagePush.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.chat.proto.Messagepush.internal__static_com_tencent_mars_sample_chat_proto_MessagePush__FieldAccessorTable; }
    }
    
    public const int TopicFieldNumber = 1;
    private bool hasTopic;
    private string topic_ = "";
    public bool HasTopic {
      get { return hasTopic; }
    }
    public string Topic {
      get { return topic_; }
    }
    
    public const int ContentFieldNumber = 2;
    private bool hasContent;
    private string content_ = "";
    public bool HasContent {
      get { return hasContent; }
    }
    public string Content {
      get { return content_; }
    }
    
    public const int FromFieldNumber = 3;
    private bool hasFrom;
    private string from_ = "";
    public bool HasFrom {
      get { return hasFrom; }
    }
    public string From {
      get { return from_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasTopic) return false;
        if (!hasContent) return false;
        if (!hasFrom) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _messagePushFieldNames;
      if (hasTopic) {
        output.WriteString(1, field_names[2], Topic);
      }
      if (hasContent) {
        output.WriteString(2, field_names[0], Content);
      }
      if (hasFrom) {
        output.WriteString(3, field_names[1], From);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Topic);
        }
        if (hasContent) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Content);
        }
        if (hasFrom) {
          size += pb::CodedOutputStream.ComputeStringSize(3, From);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MessagePush ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MessagePush ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MessagePush ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MessagePush ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MessagePush ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MessagePush ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MessagePush ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MessagePush ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MessagePush ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MessagePush ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MessagePush MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MessagePush prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MessagePush, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MessagePush cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MessagePush result;
      
      private MessagePush PrepareBuilder() {
        if (resultIsReadOnly) {
          MessagePush original = result;
          result = new MessagePush();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MessagePush MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.chat.proto.MessagePush.Descriptor; }
      }
      
      public override MessagePush DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.chat.proto.MessagePush.DefaultInstance; }
      }
      
      public override MessagePush BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MessagePush) {
          return MergeFrom((MessagePush) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MessagePush other) {
        if (other == global::com.tencent.mars.sample.chat.proto.MessagePush.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasTopic) {
          Topic = other.Topic;
        }
        if (other.HasContent) {
          Content = other.Content;
        }
        if (other.HasFrom) {
          From = other.From;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_messagePushFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _messagePushFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
            case 18: {
              result.hasContent = input.ReadString(ref result.content_);
              break;
            }
            case 26: {
              result.hasFrom = input.ReadString(ref result.from_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasTopic {
        get { return result.hasTopic; }
      }
      public string Topic {
        get { return result.Topic; }
        set { SetTopic(value); }
      }
      public Builder SetTopic(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTopic = true;
        result.topic_ = value;
        return this;
      }
      public Builder ClearTopic() {
        PrepareBuilder();
        result.hasTopic = false;
        result.topic_ = "";
        return this;
      }
      
      public bool HasContent {
        get { return result.hasContent; }
      }
      public string Content {
        get { return result.Content; }
        set { SetContent(value); }
      }
      public Builder SetContent(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasContent = true;
        result.content_ = value;
        return this;
      }
      public Builder ClearContent() {
        PrepareBuilder();
        result.hasContent = false;
        result.content_ = "";
        return this;
      }
      
      public bool HasFrom {
        get { return result.hasFrom; }
      }
      public string From {
        get { return result.From; }
        set { SetFrom(value); }
      }
      public Builder SetFrom(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFrom = true;
        result.from_ = value;
        return this;
      }
      public Builder ClearFrom() {
        PrepareBuilder();
        result.hasFrom = false;
        result.from_ = "";
        return this;
      }
    }
    static MessagePush() {
      object.ReferenceEquals(global::com.tencent.mars.sample.chat.proto.Messagepush.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
