// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.tencent.mars.sample.chat.proto {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class Topic {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.TopicRequest, global::com.tencent.mars.sample.chat.proto.TopicRequest.Builder> internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.TopicResponse, global::com.tencent.mars.sample.chat.proto.TopicResponse.Builder> internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static Topic() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "Cgt0b3BpYy5wcm90bxIiY29tLnRlbmNlbnQubWFycy5zYW1wbGUuY2hhdC5w" + 
          "cm90byIdCgxUb3BpY1JlcXVlc3QSDQoFdG9waWMYASACKAkiXQoNVG9waWNS" + 
          "ZXNwb25zZRIQCghlcnJfY29kZRgBIAIoBRIPCgdlcnJfbXNnGAIgAigJIikK" + 
          "BUVycm9yEgoKBkVSUl9PSxAAEhQKB0VSUl9TWVMQ////////////AQ==");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.TopicRequest, global::com.tencent.mars.sample.chat.proto.TopicRequest.Builder>(internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__Descriptor,
                new string[] { "Topic", });
        internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__Descriptor = Descriptor.MessageTypes[1];
        internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.chat.proto.TopicResponse, global::com.tencent.mars.sample.chat.proto.TopicResponse.Builder>(internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__Descriptor,
                new string[] { "ErrCode", "ErrMsg", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class TopicRequest : pb::GeneratedMessage<TopicRequest, TopicRequest.Builder> {
    private TopicRequest() { }
    private static readonly TopicRequest defaultInstance = new TopicRequest().MakeReadOnly();
    private static readonly string[] _topicRequestFieldNames = new string[] { "topic" };
    private static readonly uint[] _topicRequestFieldTags = new uint[] { 10 };
    public static TopicRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override TopicRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override TopicRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.chat.proto.Topic.internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<TopicRequest, TopicRequest.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.chat.proto.Topic.internal__static_com_tencent_mars_sample_chat_proto_TopicRequest__FieldAccessorTable; }
    }
    
    public const int TopicFieldNumber = 1;
    private bool hasTopic;
    private string topic_ = "";
    public bool HasTopic {
      get { return hasTopic; }
    }
    public string Topic {
      get { return topic_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasTopic) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _topicRequestFieldNames;
      if (hasTopic) {
        output.WriteString(1, field_names[0], Topic);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Topic);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static TopicRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static TopicRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static TopicRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static TopicRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static TopicRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static TopicRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static TopicRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static TopicRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static TopicRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static TopicRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private TopicRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(TopicRequest prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<TopicRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(TopicRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private TopicRequest result;
      
      private TopicRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          TopicRequest original = result;
          result = new TopicRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override TopicRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.chat.proto.TopicRequest.Descriptor; }
      }
      
      public override TopicRequest DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.chat.proto.TopicRequest.DefaultInstance; }
      }
      
      public override TopicRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is TopicRequest) {
          return MergeFrom((TopicRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(TopicRequest other) {
        if (other == global::com.tencent.mars.sample.chat.proto.TopicRequest.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasTopic) {
          Topic = other.Topic;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_topicRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _topicRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasTopic {
        get { return result.hasTopic; }
      }
      public string Topic {
        get { return result.Topic; }
        set { SetTopic(value); }
      }
      public Builder SetTopic(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTopic = true;
        result.topic_ = value;
        return this;
      }
      public Builder ClearTopic() {
        PrepareBuilder();
        result.hasTopic = false;
        result.topic_ = "";
        return this;
      }
    }
    static TopicRequest() {
      object.ReferenceEquals(global::com.tencent.mars.sample.chat.proto.Topic.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class TopicResponse : pb::GeneratedMessage<TopicResponse, TopicResponse.Builder> {
    private TopicResponse() { }
    private static readonly TopicResponse defaultInstance = new TopicResponse().MakeReadOnly();
    private static readonly string[] _topicResponseFieldNames = new string[] { "err_code", "err_msg" };
    private static readonly uint[] _topicResponseFieldTags = new uint[] { 8, 18 };
    public static TopicResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override TopicResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override TopicResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.chat.proto.Topic.internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<TopicResponse, TopicResponse.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.chat.proto.Topic.internal__static_com_tencent_mars_sample_chat_proto_TopicResponse__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static class Types {
      [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
      public enum Error {
        ERR_OK = 0,
        ERR_SYS = -1,
      }
      
    }
    #endregion
    
    public const int ErrCodeFieldNumber = 1;
    private bool hasErrCode;
    private int errCode_;
    public bool HasErrCode {
      get { return hasErrCode; }
    }
    public int ErrCode {
      get { return errCode_; }
    }
    
    public const int ErrMsgFieldNumber = 2;
    private bool hasErrMsg;
    private string errMsg_ = "";
    public bool HasErrMsg {
      get { return hasErrMsg; }
    }
    public string ErrMsg {
      get { return errMsg_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasErrCode) return false;
        if (!hasErrMsg) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _topicResponseFieldNames;
      if (hasErrCode) {
        output.WriteInt32(1, field_names[0], ErrCode);
      }
      if (hasErrMsg) {
        output.WriteString(2, field_names[1], ErrMsg);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasErrCode) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, ErrCode);
        }
        if (hasErrMsg) {
          size += pb::CodedOutputStream.ComputeStringSize(2, ErrMsg);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static TopicResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static TopicResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static TopicResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static TopicResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static TopicResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static TopicResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static TopicResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static TopicResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static TopicResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static TopicResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private TopicResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(TopicResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<TopicResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(TopicResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private TopicResponse result;
      
      private TopicResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          TopicResponse original = result;
          result = new TopicResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override TopicResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.chat.proto.TopicResponse.Descriptor; }
      }
      
      public override TopicResponse DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.chat.proto.TopicResponse.DefaultInstance; }
      }
      
      public override TopicResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is TopicResponse) {
          return MergeFrom((TopicResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(TopicResponse other) {
        if (other == global::com.tencent.mars.sample.chat.proto.TopicResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasErrCode) {
          ErrCode = other.ErrCode;
        }
        if (other.HasErrMsg) {
          ErrMsg = other.ErrMsg;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_topicResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _topicResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasErrCode = input.ReadInt32(ref result.errCode_);
              break;
            }
            case 18: {
              result.hasErrMsg = input.ReadString(ref result.errMsg_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasErrCode {
        get { return result.hasErrCode; }
      }
      public int ErrCode {
        get { return result.ErrCode; }
        set { SetErrCode(value); }
      }
      public Builder SetErrCode(int value) {
        PrepareBuilder();
        result.hasErrCode = true;
        result.errCode_ = value;
        return this;
      }
      public Builder ClearErrCode() {
        PrepareBuilder();
        result.hasErrCode = false;
        result.errCode_ = 0;
        return this;
      }
      
      public bool HasErrMsg {
        get { return result.hasErrMsg; }
      }
      public string ErrMsg {
        get { return result.ErrMsg; }
        set { SetErrMsg(value); }
      }
      public Builder SetErrMsg(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrMsg = true;
        result.errMsg_ = value;
        return this;
      }
      public Builder ClearErrMsg() {
        PrepareBuilder();
        result.hasErrMsg = false;
        result.errMsg_ = "";
        return this;
      }
    }
    static TopicResponse() {
      object.ReferenceEquals(global::com.tencent.mars.sample.chat.proto.Topic.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
