// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.tencent.mars.sample.proto {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class Main {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_proto_HelloRequest__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.HelloRequest, global::com.tencent.mars.sample.proto.HelloRequest.Builder> internal__static_com_tencent_mars_sample_proto_HelloRequest__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_proto_HelloResponse__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.HelloResponse, global::com.tencent.mars.sample.proto.HelloResponse.Builder> internal__static_com_tencent_mars_sample_proto_HelloResponse__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_proto_Conversation__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.Conversation, global::com.tencent.mars.sample.proto.Conversation.Builder> internal__static_com_tencent_mars_sample_proto_Conversation__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_proto_ConversationListRequest__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.ConversationListRequest, global::com.tencent.mars.sample.proto.ConversationListRequest.Builder> internal__static_com_tencent_mars_sample_proto_ConversationListRequest__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_com_tencent_mars_sample_proto_ConversationListResponse__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.ConversationListResponse, global::com.tencent.mars.sample.proto.ConversationListResponse.Builder> internal__static_com_tencent_mars_sample_proto_ConversationListResponse__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static Main() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "CgptYWluLnByb3RvEh1jb20udGVuY2VudC5tYXJzLnNhbXBsZS5wcm90byJA" + 
          "CgxIZWxsb1JlcXVlc3QSDAoEdXNlchgBIAIoCRIMCgR0ZXh0GAIgAigJEhQK" + 
          "DGR1bXBfY29udGVudBgDIAEoDCJGCg1IZWxsb1Jlc3BvbnNlEg8KB3JldGNv" + 
          "ZGUYASACKAUSDgoGZXJybXNnGAIgASgJEhQKDGR1bXBfY29udGVudBgDIAEo" + 
          "DCI7CgxDb252ZXJzYXRpb24SDQoFdG9waWMYASACKAkSDgoGbm90aWNlGAIg" + 
          "AigJEgwKBG5hbWUYAyACKAkihAEKF0NvbnZlcnNhdGlvbkxpc3RSZXF1ZXN0" + 
          "EhQKDGFjY2Vzc190b2tlbhgBIAIoCRIMCgR0eXBlGAIgAigFIkUKCkZpbHRl" + 
          "clR5cGUSCwoHREVGQVVMVBAAEgcKA0FMTBABEgsKB05FQVJfQlkQAhILCgdG" + 
          "UklFTkRTEAMSBwoDSE9UEAQiVQoYQ29udmVyc2F0aW9uTGlzdFJlc3BvbnNl" + 
          "EjkKBGxpc3QYASADKAsyKy5jb20udGVuY2VudC5tYXJzLnNhbXBsZS5wcm90" + 
          "by5Db252ZXJzYXRpb24q0QEKBUNtZElEEhsKDkNNRF9JRF9JTlZBTElEEP//" + 
          "/////////wESEgoOQ01EX0lEX1VOS05PV04QABIQCgxDTURfSURfSEVMTE8Q" + 
          "ARIPCgtDTURfSURfQVVUSBACEhcKE0NNRF9JRF9TRU5EX01FU1NBR0UQAxIc" + 
          "ChhDTURfSURfQ09OVkVSU0FUSU9OX0xJU1QQBBIUChBDTURfSURfSk9JTlRP" + 
          "UElDEAUSFAoQQ01EX0lEX0xFRlRUT1BJQxAHEhEKDUNNRF9JRF9IRUxMTzIQ" + 
          "CA==");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_tencent_mars_sample_proto_HelloRequest__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_tencent_mars_sample_proto_HelloRequest__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.HelloRequest, global::com.tencent.mars.sample.proto.HelloRequest.Builder>(internal__static_com_tencent_mars_sample_proto_HelloRequest__Descriptor,
                new string[] { "User", "Text", "DumpContent", });
        internal__static_com_tencent_mars_sample_proto_HelloResponse__Descriptor = Descriptor.MessageTypes[1];
        internal__static_com_tencent_mars_sample_proto_HelloResponse__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.HelloResponse, global::com.tencent.mars.sample.proto.HelloResponse.Builder>(internal__static_com_tencent_mars_sample_proto_HelloResponse__Descriptor,
                new string[] { "Retcode", "Errmsg", "DumpContent", });
        internal__static_com_tencent_mars_sample_proto_Conversation__Descriptor = Descriptor.MessageTypes[2];
        internal__static_com_tencent_mars_sample_proto_Conversation__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.Conversation, global::com.tencent.mars.sample.proto.Conversation.Builder>(internal__static_com_tencent_mars_sample_proto_Conversation__Descriptor,
                new string[] { "Topic", "Notice", "Name", });
        internal__static_com_tencent_mars_sample_proto_ConversationListRequest__Descriptor = Descriptor.MessageTypes[3];
        internal__static_com_tencent_mars_sample_proto_ConversationListRequest__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.ConversationListRequest, global::com.tencent.mars.sample.proto.ConversationListRequest.Builder>(internal__static_com_tencent_mars_sample_proto_ConversationListRequest__Descriptor,
                new string[] { "AccessToken", "Type", });
        internal__static_com_tencent_mars_sample_proto_ConversationListResponse__Descriptor = Descriptor.MessageTypes[4];
        internal__static_com_tencent_mars_sample_proto_ConversationListResponse__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.tencent.mars.sample.proto.ConversationListResponse, global::com.tencent.mars.sample.proto.ConversationListResponse.Builder>(internal__static_com_tencent_mars_sample_proto_ConversationListResponse__Descriptor,
                new string[] { "List", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum CmdID {
    CMD_ID_INVALID = -1,
    CMD_ID_UNKNOWN = 0,
    CMD_ID_HELLO = 1,
    CMD_ID_AUTH = 2,
    CMD_ID_SEND_MESSAGE = 3,
    CMD_ID_CONVERSATION_LIST = 4,
    CMD_ID_JOINTOPIC = 5,
    CMD_ID_LEFTTOPIC = 7,
    CMD_ID_HELLO2 = 8,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class HelloRequest : pb::GeneratedMessage<HelloRequest, HelloRequest.Builder> {
    private HelloRequest() { }
    private static readonly HelloRequest defaultInstance = new HelloRequest().MakeReadOnly();
    private static readonly string[] _helloRequestFieldNames = new string[] { "dump_content", "text", "user" };
    private static readonly uint[] _helloRequestFieldTags = new uint[] { 26, 18, 10 };
    public static HelloRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override HelloRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override HelloRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_HelloRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<HelloRequest, HelloRequest.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_HelloRequest__FieldAccessorTable; }
    }
    
    public const int UserFieldNumber = 1;
    private bool hasUser;
    private string user_ = "";
    public bool HasUser {
      get { return hasUser; }
    }
    public string User {
      get { return user_; }
    }
    
    public const int TextFieldNumber = 2;
    private bool hasText;
    private string text_ = "";
    public bool HasText {
      get { return hasText; }
    }
    public string Text {
      get { return text_; }
    }
    
    public const int DumpContentFieldNumber = 3;
    private bool hasDumpContent;
    private pb::ByteString dumpContent_ = pb::ByteString.Empty;
    public bool HasDumpContent {
      get { return hasDumpContent; }
    }
    public pb::ByteString DumpContent {
      get { return dumpContent_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasUser) return false;
        if (!hasText) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _helloRequestFieldNames;
      if (hasUser) {
        output.WriteString(1, field_names[2], User);
      }
      if (hasText) {
        output.WriteString(2, field_names[1], Text);
      }
      if (hasDumpContent) {
        output.WriteBytes(3, field_names[0], DumpContent);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasUser) {
          size += pb::CodedOutputStream.ComputeStringSize(1, User);
        }
        if (hasText) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Text);
        }
        if (hasDumpContent) {
          size += pb::CodedOutputStream.ComputeBytesSize(3, DumpContent);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static HelloRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static HelloRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static HelloRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static HelloRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static HelloRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static HelloRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static HelloRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static HelloRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static HelloRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static HelloRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private HelloRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(HelloRequest prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<HelloRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(HelloRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private HelloRequest result;
      
      private HelloRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          HelloRequest original = result;
          result = new HelloRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override HelloRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.proto.HelloRequest.Descriptor; }
      }
      
      public override HelloRequest DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.HelloRequest.DefaultInstance; }
      }
      
      public override HelloRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is HelloRequest) {
          return MergeFrom((HelloRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(HelloRequest other) {
        if (other == global::com.tencent.mars.sample.proto.HelloRequest.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasUser) {
          User = other.User;
        }
        if (other.HasText) {
          Text = other.Text;
        }
        if (other.HasDumpContent) {
          DumpContent = other.DumpContent;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_helloRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _helloRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasUser = input.ReadString(ref result.user_);
              break;
            }
            case 18: {
              result.hasText = input.ReadString(ref result.text_);
              break;
            }
            case 26: {
              result.hasDumpContent = input.ReadBytes(ref result.dumpContent_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasUser {
        get { return result.hasUser; }
      }
      public string User {
        get { return result.User; }
        set { SetUser(value); }
      }
      public Builder SetUser(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasUser = true;
        result.user_ = value;
        return this;
      }
      public Builder ClearUser() {
        PrepareBuilder();
        result.hasUser = false;
        result.user_ = "";
        return this;
      }
      
      public bool HasText {
        get { return result.hasText; }
      }
      public string Text {
        get { return result.Text; }
        set { SetText(value); }
      }
      public Builder SetText(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder ClearText() {
        PrepareBuilder();
        result.hasText = false;
        result.text_ = "";
        return this;
      }
      
      public bool HasDumpContent {
        get { return result.hasDumpContent; }
      }
      public pb::ByteString DumpContent {
        get { return result.DumpContent; }
        set { SetDumpContent(value); }
      }
      public Builder SetDumpContent(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasDumpContent = true;
        result.dumpContent_ = value;
        return this;
      }
      public Builder ClearDumpContent() {
        PrepareBuilder();
        result.hasDumpContent = false;
        result.dumpContent_ = pb::ByteString.Empty;
        return this;
      }
    }
    static HelloRequest() {
      object.ReferenceEquals(global::com.tencent.mars.sample.proto.Main.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class HelloResponse : pb::GeneratedMessage<HelloResponse, HelloResponse.Builder> {
    private HelloResponse() { }
    private static readonly HelloResponse defaultInstance = new HelloResponse().MakeReadOnly();
    private static readonly string[] _helloResponseFieldNames = new string[] { "dump_content", "errmsg", "retcode" };
    private static readonly uint[] _helloResponseFieldTags = new uint[] { 26, 18, 8 };
    public static HelloResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override HelloResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override HelloResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_HelloResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<HelloResponse, HelloResponse.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_HelloResponse__FieldAccessorTable; }
    }
    
    public const int RetcodeFieldNumber = 1;
    private bool hasRetcode;
    private int retcode_;
    public bool HasRetcode {
      get { return hasRetcode; }
    }
    public int Retcode {
      get { return retcode_; }
    }
    
    public const int ErrmsgFieldNumber = 2;
    private bool hasErrmsg;
    private string errmsg_ = "";
    public bool HasErrmsg {
      get { return hasErrmsg; }
    }
    public string Errmsg {
      get { return errmsg_; }
    }
    
    public const int DumpContentFieldNumber = 3;
    private bool hasDumpContent;
    private pb::ByteString dumpContent_ = pb::ByteString.Empty;
    public bool HasDumpContent {
      get { return hasDumpContent; }
    }
    public pb::ByteString DumpContent {
      get { return dumpContent_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasRetcode) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _helloResponseFieldNames;
      if (hasRetcode) {
        output.WriteInt32(1, field_names[2], Retcode);
      }
      if (hasErrmsg) {
        output.WriteString(2, field_names[1], Errmsg);
      }
      if (hasDumpContent) {
        output.WriteBytes(3, field_names[0], DumpContent);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasRetcode) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, Retcode);
        }
        if (hasErrmsg) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Errmsg);
        }
        if (hasDumpContent) {
          size += pb::CodedOutputStream.ComputeBytesSize(3, DumpContent);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static HelloResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static HelloResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static HelloResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static HelloResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static HelloResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static HelloResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static HelloResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static HelloResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static HelloResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static HelloResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private HelloResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(HelloResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<HelloResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(HelloResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private HelloResponse result;
      
      private HelloResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          HelloResponse original = result;
          result = new HelloResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override HelloResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.proto.HelloResponse.Descriptor; }
      }
      
      public override HelloResponse DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.HelloResponse.DefaultInstance; }
      }
      
      public override HelloResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is HelloResponse) {
          return MergeFrom((HelloResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(HelloResponse other) {
        if (other == global::com.tencent.mars.sample.proto.HelloResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasRetcode) {
          Retcode = other.Retcode;
        }
        if (other.HasErrmsg) {
          Errmsg = other.Errmsg;
        }
        if (other.HasDumpContent) {
          DumpContent = other.DumpContent;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_helloResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _helloResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasRetcode = input.ReadInt32(ref result.retcode_);
              break;
            }
            case 18: {
              result.hasErrmsg = input.ReadString(ref result.errmsg_);
              break;
            }
            case 26: {
              result.hasDumpContent = input.ReadBytes(ref result.dumpContent_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasRetcode {
        get { return result.hasRetcode; }
      }
      public int Retcode {
        get { return result.Retcode; }
        set { SetRetcode(value); }
      }
      public Builder SetRetcode(int value) {
        PrepareBuilder();
        result.hasRetcode = true;
        result.retcode_ = value;
        return this;
      }
      public Builder ClearRetcode() {
        PrepareBuilder();
        result.hasRetcode = false;
        result.retcode_ = 0;
        return this;
      }
      
      public bool HasErrmsg {
        get { return result.hasErrmsg; }
      }
      public string Errmsg {
        get { return result.Errmsg; }
        set { SetErrmsg(value); }
      }
      public Builder SetErrmsg(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrmsg = true;
        result.errmsg_ = value;
        return this;
      }
      public Builder ClearErrmsg() {
        PrepareBuilder();
        result.hasErrmsg = false;
        result.errmsg_ = "";
        return this;
      }
      
      public bool HasDumpContent {
        get { return result.hasDumpContent; }
      }
      public pb::ByteString DumpContent {
        get { return result.DumpContent; }
        set { SetDumpContent(value); }
      }
      public Builder SetDumpContent(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasDumpContent = true;
        result.dumpContent_ = value;
        return this;
      }
      public Builder ClearDumpContent() {
        PrepareBuilder();
        result.hasDumpContent = false;
        result.dumpContent_ = pb::ByteString.Empty;
        return this;
      }
    }
    static HelloResponse() {
      object.ReferenceEquals(global::com.tencent.mars.sample.proto.Main.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class Conversation : pb::GeneratedMessage<Conversation, Conversation.Builder> {
    private Conversation() { }
    private static readonly Conversation defaultInstance = new Conversation().MakeReadOnly();
    private static readonly string[] _conversationFieldNames = new string[] { "name", "notice", "topic" };
    private static readonly uint[] _conversationFieldTags = new uint[] { 26, 18, 10 };
    public static Conversation DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override Conversation DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override Conversation ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_Conversation__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<Conversation, Conversation.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_Conversation__FieldAccessorTable; }
    }
    
    public const int TopicFieldNumber = 1;
    private bool hasTopic;
    private string topic_ = "";
    public bool HasTopic {
      get { return hasTopic; }
    }
    public string Topic {
      get { return topic_; }
    }
    
    public const int NoticeFieldNumber = 2;
    private bool hasNotice;
    private string notice_ = "";
    public bool HasNotice {
      get { return hasNotice; }
    }
    public string Notice {
      get { return notice_; }
    }
    
    public const int NameFieldNumber = 3;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasTopic) return false;
        if (!hasNotice) return false;
        if (!hasName) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _conversationFieldNames;
      if (hasTopic) {
        output.WriteString(1, field_names[2], Topic);
      }
      if (hasNotice) {
        output.WriteString(2, field_names[1], Notice);
      }
      if (hasName) {
        output.WriteString(3, field_names[0], Name);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Topic);
        }
        if (hasNotice) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Notice);
        }
        if (hasName) {
          size += pb::CodedOutputStream.ComputeStringSize(3, Name);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static Conversation ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Conversation ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Conversation ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Conversation ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Conversation ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Conversation ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Conversation ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static Conversation ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static Conversation ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Conversation ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private Conversation MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(Conversation prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<Conversation, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(Conversation cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private Conversation result;
      
      private Conversation PrepareBuilder() {
        if (resultIsReadOnly) {
          Conversation original = result;
          result = new Conversation();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override Conversation MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.proto.Conversation.Descriptor; }
      }
      
      public override Conversation DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.Conversation.DefaultInstance; }
      }
      
      public override Conversation BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is Conversation) {
          return MergeFrom((Conversation) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(Conversation other) {
        if (other == global::com.tencent.mars.sample.proto.Conversation.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasTopic) {
          Topic = other.Topic;
        }
        if (other.HasNotice) {
          Notice = other.Notice;
        }
        if (other.HasName) {
          Name = other.Name;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_conversationFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _conversationFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
            case 18: {
              result.hasNotice = input.ReadString(ref result.notice_);
              break;
            }
            case 26: {
              result.hasName = input.ReadString(ref result.name_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasTopic {
        get { return result.hasTopic; }
      }
      public string Topic {
        get { return result.Topic; }
        set { SetTopic(value); }
      }
      public Builder SetTopic(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTopic = true;
        result.topic_ = value;
        return this;
      }
      public Builder ClearTopic() {
        PrepareBuilder();
        result.hasTopic = false;
        result.topic_ = "";
        return this;
      }
      
      public bool HasNotice {
        get { return result.hasNotice; }
      }
      public string Notice {
        get { return result.Notice; }
        set { SetNotice(value); }
      }
      public Builder SetNotice(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasNotice = true;
        result.notice_ = value;
        return this;
      }
      public Builder ClearNotice() {
        PrepareBuilder();
        result.hasNotice = false;
        result.notice_ = "";
        return this;
      }
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
    }
    static Conversation() {
      object.ReferenceEquals(global::com.tencent.mars.sample.proto.Main.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class ConversationListRequest : pb::GeneratedMessage<ConversationListRequest, ConversationListRequest.Builder> {
    private ConversationListRequest() { }
    private static readonly ConversationListRequest defaultInstance = new ConversationListRequest().MakeReadOnly();
    private static readonly string[] _conversationListRequestFieldNames = new string[] { "access_token", "type" };
    private static readonly uint[] _conversationListRequestFieldTags = new uint[] { 10, 16 };
    public static ConversationListRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ConversationListRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ConversationListRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_ConversationListRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ConversationListRequest, ConversationListRequest.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_ConversationListRequest__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static class Types {
      [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
      public enum FilterType {
        DEFAULT = 0,
        ALL = 1,
        NEAR_BY = 2,
        FRIENDS = 3,
        HOT = 4,
      }
      
    }
    #endregion
    
    public const int AccessTokenFieldNumber = 1;
    private bool hasAccessToken;
    private string accessToken_ = "";
    public bool HasAccessToken {
      get { return hasAccessToken; }
    }
    public string AccessToken {
      get { return accessToken_; }
    }
    
    public const int TypeFieldNumber = 2;
    private bool hasType;
    private int type_;
    public bool HasType {
      get { return hasType; }
    }
    public int Type {
      get { return type_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasAccessToken) return false;
        if (!hasType) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _conversationListRequestFieldNames;
      if (hasAccessToken) {
        output.WriteString(1, field_names[0], AccessToken);
      }
      if (hasType) {
        output.WriteInt32(2, field_names[1], Type);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasAccessToken) {
          size += pb::CodedOutputStream.ComputeStringSize(1, AccessToken);
        }
        if (hasType) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, Type);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static ConversationListRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ConversationListRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ConversationListRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ConversationListRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ConversationListRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ConversationListRequest prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<ConversationListRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ConversationListRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ConversationListRequest result;
      
      private ConversationListRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          ConversationListRequest original = result;
          result = new ConversationListRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ConversationListRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.proto.ConversationListRequest.Descriptor; }
      }
      
      public override ConversationListRequest DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.ConversationListRequest.DefaultInstance; }
      }
      
      public override ConversationListRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ConversationListRequest) {
          return MergeFrom((ConversationListRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ConversationListRequest other) {
        if (other == global::com.tencent.mars.sample.proto.ConversationListRequest.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasAccessToken) {
          AccessToken = other.AccessToken;
        }
        if (other.HasType) {
          Type = other.Type;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_conversationListRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _conversationListRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasAccessToken = input.ReadString(ref result.accessToken_);
              break;
            }
            case 16: {
              result.hasType = input.ReadInt32(ref result.type_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasAccessToken {
        get { return result.hasAccessToken; }
      }
      public string AccessToken {
        get { return result.AccessToken; }
        set { SetAccessToken(value); }
      }
      public Builder SetAccessToken(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasAccessToken = true;
        result.accessToken_ = value;
        return this;
      }
      public Builder ClearAccessToken() {
        PrepareBuilder();
        result.hasAccessToken = false;
        result.accessToken_ = "";
        return this;
      }
      
      public bool HasType {
        get { return result.hasType; }
      }
      public int Type {
        get { return result.Type; }
        set { SetType(value); }
      }
      public Builder SetType(int value) {
        PrepareBuilder();
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder ClearType() {
        PrepareBuilder();
        result.hasType = false;
        result.type_ = 0;
        return this;
      }
    }
    static ConversationListRequest() {
      object.ReferenceEquals(global::com.tencent.mars.sample.proto.Main.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class ConversationListResponse : pb::GeneratedMessage<ConversationListResponse, ConversationListResponse.Builder> {
    private ConversationListResponse() { }
    private static readonly ConversationListResponse defaultInstance = new ConversationListResponse().MakeReadOnly();
    private static readonly string[] _conversationListResponseFieldNames = new string[] { "list" };
    private static readonly uint[] _conversationListResponseFieldTags = new uint[] { 10 };
    public static ConversationListResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ConversationListResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ConversationListResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_ConversationListResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ConversationListResponse, ConversationListResponse.Builder> InternalFieldAccessors {
      get { return global::com.tencent.mars.sample.proto.Main.internal__static_com_tencent_mars_sample_proto_ConversationListResponse__FieldAccessorTable; }
    }
    
    public const int ListFieldNumber = 1;
    private pbc::PopsicleList<global::com.tencent.mars.sample.proto.Conversation> list_ = new pbc::PopsicleList<global::com.tencent.mars.sample.proto.Conversation>();
    public scg::IList<global::com.tencent.mars.sample.proto.Conversation> ListList {
      get { return list_; }
    }
    public int ListCount {
      get { return list_.Count; }
    }
    public global::com.tencent.mars.sample.proto.Conversation GetList(int index) {
      return list_[index];
    }
    
    public override bool IsInitialized {
      get {
        foreach (global::com.tencent.mars.sample.proto.Conversation element in ListList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _conversationListResponseFieldNames;
      if (list_.Count > 0) {
        output.WriteMessageArray(1, field_names[0], list_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        foreach (global::com.tencent.mars.sample.proto.Conversation element in ListList) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, element);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static ConversationListResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ConversationListResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ConversationListResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ConversationListResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ConversationListResponse MakeReadOnly() {
      list_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ConversationListResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<ConversationListResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ConversationListResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ConversationListResponse result;
      
      private ConversationListResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          ConversationListResponse original = result;
          result = new ConversationListResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ConversationListResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.tencent.mars.sample.proto.ConversationListResponse.Descriptor; }
      }
      
      public override ConversationListResponse DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.ConversationListResponse.DefaultInstance; }
      }
      
      public override ConversationListResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ConversationListResponse) {
          return MergeFrom((ConversationListResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ConversationListResponse other) {
        if (other == global::com.tencent.mars.sample.proto.ConversationListResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.list_.Count != 0) {
          result.list_.Add(other.list_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_conversationListResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _conversationListResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadMessageArray(tag, field_name, result.list_, global::com.tencent.mars.sample.proto.Conversation.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<global::com.tencent.mars.sample.proto.Conversation> ListList {
        get { return PrepareBuilder().list_; }
      }
      public int ListCount {
        get { return result.ListCount; }
      }
      public global::com.tencent.mars.sample.proto.Conversation GetList(int index) {
        return result.GetList(index);
      }
      public Builder SetList(int index, global::com.tencent.mars.sample.proto.Conversation value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.list_[index] = value;
        return this;
      }
      public Builder SetList(int index, global::com.tencent.mars.sample.proto.Conversation.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.list_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddList(global::com.tencent.mars.sample.proto.Conversation value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.list_.Add(value);
        return this;
      }
      public Builder AddList(global::com.tencent.mars.sample.proto.Conversation.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.list_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeList(scg::IEnumerable<global::com.tencent.mars.sample.proto.Conversation> values) {
        PrepareBuilder();
        result.list_.Add(values);
        return this;
      }
      public Builder ClearList() {
        PrepareBuilder();
        result.list_.Clear();
        return this;
      }
    }
    static ConversationListResponse() {
      object.ReferenceEquals(global::com.tencent.mars.sample.proto.Main.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
